// TypeScript client function generation.
//
// Generates `client.ts` with namespaced RPC call functions
// that import from `types.ts` and `errors.ts`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use specta::ResolvedTypes;

use crate::config::Config;
use crate::naming::split_namespace;
use crate::{GenerateError, ProcedureInfo};

const HEADER: &str = "// Auto-generated by teleport-rs. DO NOT EDIT.\n";

/// Generate the contents of `client.ts`.
///
/// Groups procedures by namespace and generates typed RPC call functions.
pub(crate) fn generate_client(
    procedures: &[ProcedureInfo],
    config: &Config,
    resolved_types: &ResolvedTypes,
) -> Result<String, GenerateError> {
    let ts_exporter = specta_typescript::Typescript::default();

    // Resolve all TS type strings and collect import names.
    let mut type_imports: BTreeSet<String> = BTreeSet::new();
    let mut error_imports: BTreeSet<String> = BTreeSet::new();

    // Always import RpcResult from errors.
    error_imports.insert("RpcResult".to_owned());

    // Group procedures by namespace.
    let mut namespaces: BTreeMap<String, Vec<ProcedureEntry>> = BTreeMap::new();

    for proc in procedures {
        let input_ts = crate::ts_utils::datatype_to_ts(&ts_exporter, resolved_types, &proc.input_type)?;
        let output_ts = crate::ts_utils::datatype_to_ts(&ts_exporter, resolved_types, &proc.output_type)?;
        let error_ts = crate::ts_utils::datatype_to_ts(&ts_exporter, resolved_types, &proc.error_type)?;

        // Collect non-primitive type names for imports.
        collect_type_names(&proc.input_type, resolved_types, &mut type_imports);
        collect_type_names(&proc.output_type, resolved_types, &mut type_imports);
        collect_type_names(&proc.error_type, resolved_types, &mut type_imports);

        let (ns, method_name) = split_namespace(&proc.name);
        let namespace = if ns.is_empty() {
            "_root".to_owned()
        } else {
            ns.to_owned()
        };

        let output_ts_return = if is_unit_type(&output_ts) {
            "void".to_owned()
        } else {
            output_ts
        };

        let is_void_input = is_unit_type(&input_ts);

        namespaces.entry(namespace).or_default().push(ProcedureEntry {
            method_name: method_name.to_owned(),
            http_method: proc.method.as_str().to_owned(),
            path: proc.path.clone(),
            doc: proc.doc.clone(),
            input_ts: if is_void_input {
                None
            } else {
                Some(input_ts)
            },
            output_ts: output_ts_return,
            error_ts,
        });
    }

    // Remove primitive type names from imports (they don't need importing).
    type_imports.retain(|name| !crate::ts_utils::is_ts_primitive(name));

    // Build output.
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push('\n');

    // Import rpc from the client runtime package.
    let _ = writeln!(
        out,
        "import {{ rpc }} from \"{}\";",
        config.client_import_path.as_deref().unwrap_or("@teleport-rs/client")
    );

    // Import error types.
    if !error_imports.is_empty() {
        let imports: Vec<&str> = error_imports.iter().map(String::as_str).collect();
        let _ = writeln!(out, "import type {{ {} }} from \"./errors\";", imports.join(", "));
    }

    // Import data types from types.ts.
    if !type_imports.is_empty() {
        let imports: Vec<&str> = type_imports.iter().map(String::as_str).collect();
        let _ = writeln!(out, "import type {{ {} }} from \"./types\";", imports.join(", "));
    }

    // Generate namespace objects.
    for (ns_name, entries) in &namespaces {
        out.push('\n');
        let _ = writeln!(out, "export const {ns_name} = {{");

        for (i, entry) in entries.iter().enumerate() {
            // JSDoc comment.
            if entry.doc.is_empty() {
                let _ = writeln!(out, "  /** {} {} */", entry.http_method, entry.path);
            } else {
                let _ = writeln!(out, "  /**");
                for line in entry.doc.lines() {
                    let _ = writeln!(out, "   * {line}");
                }
                let _ = writeln!(
                    out,
                    "   * {} {}",
                    entry.http_method, entry.path
                );
                let _ = writeln!(out, "   */");
            }

            // Function signature.
            let param = entry
                .input_ts
                .as_ref()
                .map_or_else(String::new, |ts| format!("input: {ts}"));

            let rpc_arg = if entry.input_ts.is_some() {
                "input"
            } else {
                "undefined"
            };

            let _ = write!(
                out,
                "  {name}: ({param}): Promise<RpcResult<{output}, {error}>> =>\n    rpc(\"{method}\", \"{path}\", {rpc_arg})",
                name = entry.method_name,
                output = entry.output_ts,
                error = entry.error_ts,
                method = entry.http_method,
                path = entry.path,
            );

            if i < entries.len() - 1 {
                out.push_str(",\n\n");
            } else {
                out.push('\n');
            }
        }

        out.push_str("};\n");
    }

    Ok(out)
}

struct ProcedureEntry {
    method_name: String,
    http_method: String,
    path: String,
    doc: String,
    input_ts: Option<String>,
    output_ts: String,
    error_ts: String,
}

/// Recursively collect named type references from a `DataType`.
fn collect_type_names(
    dt: &specta::datatype::DataType,
    resolved_types: &ResolvedTypes,
    names: &mut BTreeSet<String>,
) {
    use specta::datatype::{DataType, Reference};

    match dt {
        DataType::Reference(Reference::Named(named_ref)) => {
            if let Some(ndt) = named_ref.get(resolved_types.as_types()) {
                names.insert(ndt.name().to_string());
            }
            // Also collect from generic arguments.
            for (_generic, arg_dt) in named_ref.generics() {
                collect_type_names(arg_dt, resolved_types, names);
            }
        }
        DataType::Nullable(inner) => {
            collect_type_names(inner, resolved_types, names);
        }
        DataType::List(list) => {
            collect_type_names(list.ty(), resolved_types, names);
        }
        DataType::Map(map) => {
            collect_type_names(map.key_ty(), resolved_types, names);
            collect_type_names(map.value_ty(), resolved_types, names);
        }
        DataType::Tuple(tuple) => {
            for element in tuple.elements() {
                collect_type_names(element, resolved_types, names);
            }
        }
        DataType::Struct(s) => {
            use specta::datatype::Fields;
            match s.fields() {
                Fields::Named(fields) => {
                    for (_name, field) in fields.fields() {
                        if let Some(ty) = field.ty() {
                            collect_type_names(ty, resolved_types, names);
                        }
                    }
                }
                Fields::Unnamed(fields) => {
                    for field in fields.fields() {
                        if let Some(ty) = field.ty() {
                            collect_type_names(ty, resolved_types, names);
                        }
                    }
                }
                Fields::Unit => {}
            }
        }
        DataType::Enum(e) => {
            for (_name, variant) in e.variants() {
                use specta::datatype::Fields;
                match variant.fields() {
                    Fields::Named(fields) => {
                        for (_name, field) in fields.fields() {
                            if let Some(ty) = field.ty() {
                            collect_type_names(ty, resolved_types, names);
                        }
                        }
                    }
                    Fields::Unnamed(fields) => {
                        for field in fields.fields() {
                            if let Some(ty) = field.ty() {
                            collect_type_names(ty, resolved_types, names);
                        }
                        }
                    }
                    Fields::Unit => {}
                }
            }
        }
        DataType::Primitive(_) | DataType::Reference(_) => {}
    }
}

/// Returns `true` for TS representations of the unit type.
fn is_unit_type(ts: &str) -> bool {
    ts == "null" || ts == "[]"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, Naming, NamespaceStyle};
    use specta::datatype::{DataType, Primitive, Tuple};
    use specta::{Type, Types};
    use std::path::PathBuf;

    #[derive(Debug, Clone, specta::Type)]
    #[allow(dead_code)]
    struct TestUser {
        id: String,
        name: String,
    }

    #[derive(Debug, Clone, specta::Type)]
    #[allow(dead_code)]
    struct GetUserInput {
        id: String,
    }

    /// Helper to get the `DataType` for the TS `never` type.
    fn never_datatype() -> DataType {
        <specta_typescript::Never as Type>::definition(&mut Types::default())
    }

    fn test_config() -> Config {
        Config {
            output_dir: PathBuf::from("/tmp/test"),
            namespace_style: NamespaceStyle::ModulePath,
            naming: Naming::default(),
            include_manifest: false,
            route_prefix: "/rpc".to_owned(),
            client_import_path: None,
        }
    }

    #[test]
    fn generates_namespace_with_procedure() {
        let mut types = Types::default();
        let input_dt = <GetUserInput as Type>::definition(&mut types);
        let output_dt = <TestUser as Type>::definition(&mut types);
        let resolved = ResolvedTypes::from_resolved_types(types);

        let proc = ProcedureInfo {
            name: "users.getUser".to_owned(),
            method: crate::HttpMethod::Get,
            path: "/rpc/users.getUser".to_owned(),
            doc: "Get a user by ID".to_owned(),
            input_type: input_dt,
            output_type: output_dt,
            error_type: never_datatype(),
        };

        let config = test_config();
        let output = generate_client(&[proc], &config, &resolved).expect("should generate");

        assert!(output.contains("export const users = {"));
        assert!(output.contains("getUser"));
        assert!(output.contains("rpc(\"GET\""));
        assert!(output.contains("/rpc/users.getUser"));
        assert!(output.contains("@teleport-rs/client"));
    }

    #[test]
    fn void_input_passes_undefined() {
        let types = Types::default();
        let resolved = ResolvedTypes::from_resolved_types(types);

        let proc = ProcedureInfo {
            name: "health.check".to_owned(),
            method: crate::HttpMethod::Get,
            path: "/rpc/health.check".to_owned(),
            doc: String::new(),
            input_type: DataType::Tuple(Tuple::new(vec![])),
            output_type: DataType::Primitive(Primitive::str),
            error_type: never_datatype(),
        };

        let config = test_config();
        let output = generate_client(&[proc], &config, &resolved).expect("should generate");

        assert!(output.contains("undefined"));
        assert!(output.contains("(): Promise<"));
    }
}
