// Error type generation for TypeScript.
//
// Generates `errors.ts` with AppError<T>, TransportError,
// RpcResult, and procedure-specific error type aliases.

use std::fmt::Write as _;

use specta::ResolvedTypes;

use crate::{GenerateError, ProcedureInfo};

const HEADER: &str = "// Auto-generated by teleport-rs. DO NOT EDIT.\n";

/// The hardcoded base error types that every generated project needs.
const BASE_TYPES: &str = r#"export type AppError<T = never> =
  | { type: "Unauthorized" }
  | { type: "Forbidden" }
  | { type: "NotFound" }
  | { type: "BadRequest"; message: string }
  | { type: "Internal"; message: string }
  | { type: "RateLimited" }
  | { type: "Detail"; detail: T };

export type TransportError =
  | { type: "NetworkError"; message: string }
  | { type: "SerializationError"; message: string }
  | { type: "Timeout"; message: string }
  | { type: "ServerError"; status: number; body: string };

export type RpcResult<T, E = never> =
  | { ok: true; data: T }
  | { ok: false; error: AppError<E> }
  | { ok: false; transport: TransportError };
"#;

/// Generate the contents of `errors.ts`.
///
/// Outputs the hardcoded `AppError`, `TransportError`, and `RpcResult` types,
/// followed by procedure-specific error type aliases for any procedure whose
/// error detail type is not `never`.
pub(crate) fn generate_errors(
    procedures: &[ProcedureInfo],
    resolved_types: &ResolvedTypes,
) -> Result<String, GenerateError> {
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(BASE_TYPES);

    // Collect procedure-specific error aliases.
    let ts_exporter = specta_typescript::Typescript::default();
    let mut aliases = Vec::new();
    let mut type_imports = Vec::new();

    for proc in procedures {
        let error_ts = crate::ts_utils::datatype_to_ts(&ts_exporter, resolved_types, &proc.error_type)?;

        if error_ts == "never" {
            continue;
        }

        // Derive a PascalCase alias name from the procedure name.
        // "users.getUser" -> "GetUserError"
        let (_ns, method) = crate::naming::split_namespace(&proc.name);
        let alias_name = format!("{}Error", crate::naming::snake_to_pascal(method));

        aliases.push((alias_name, error_ts.clone()));

        // Track the error detail type name for the import list (only if it's
        // a named type reference, not an inline primitive).
        if !crate::ts_utils::is_ts_primitive(&error_ts) {
            type_imports.push(error_ts);
        }
    }

    // Emit import for error detail types that live in types.ts.
    if !type_imports.is_empty() {
        type_imports.sort();
        type_imports.dedup();
        out.push('\n');
        let _ = writeln!(out, "import type {{ {} }} from \"./types\";", type_imports.join(", "));
    }

    // Emit procedure-specific error aliases.
    if !aliases.is_empty() {
        out.push('\n');
        out.push_str("// Procedure-specific error aliases\n");
        for (alias_name, error_ts) in &aliases {
            let _ = writeln!(out, "export type {alias_name} = AppError<{error_ts}>;");
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use specta::{Type, Types};

    #[derive(Debug, Clone, specta::Type)]
    #[allow(dead_code)]
    struct LoginErrorDetail {
        invalid_credentials: bool,
        account_locked: bool,
    }

    /// Helper to get the `DataType` for the TS `never` type.
    fn never_datatype() -> specta::datatype::DataType {
        <specta_typescript::Never as Type>::definition(&mut Types::default())
    }

    #[test]
    fn base_types_always_present() {
        let types = Types::default();
        let resolved = ResolvedTypes::from_resolved_types(types);
        let output = generate_errors(&[], &resolved).expect("should generate");

        assert!(output.contains("export type AppError<T = never>"));
        assert!(output.contains("export type TransportError"));
        assert!(output.contains("export type RpcResult<T, E = never>"));
    }

    #[test]
    fn generates_error_alias_for_procedure() {
        let mut types = Types::default();
        // Register the type AND get its DataType reference from the same collection.
        let error_dt = <LoginErrorDetail as Type>::definition(&mut types);
        let resolved = ResolvedTypes::from_resolved_types(types);

        let proc = ProcedureInfo {
            name: "auth.login".to_owned(),
            method: crate::HttpMethod::Post,
            path: "/rpc/auth.login".to_owned(),
            doc: String::new(),
            input_type: specta::datatype::DataType::Primitive(specta::datatype::Primitive::str),
            output_type: specta::datatype::DataType::Primitive(specta::datatype::Primitive::str),
            error_type: error_dt,
        };

        let output = generate_errors(&[proc], &resolved).expect("should generate");
        assert!(output.contains("LoginError"), "missing LoginError alias in:\n{output}");
        assert!(output.contains("AppError<LoginErrorDetail>"), "missing AppError<LoginErrorDetail> in:\n{output}");
    }

    #[test]
    fn skips_never_error_types() {
        let types = Types::default();
        let resolved = ResolvedTypes::from_resolved_types(types);

        let proc = ProcedureInfo {
            name: "health.check".to_owned(),
            method: crate::HttpMethod::Get,
            path: "/rpc/health.check".to_owned(),
            doc: String::new(),
            input_type: specta::datatype::DataType::Tuple(specta::datatype::Tuple::new(vec![])),
            output_type: specta::datatype::DataType::Tuple(specta::datatype::Tuple::new(vec![])),
            error_type: never_datatype(),
        };

        let output = generate_errors(&[proc], &resolved).expect("should generate");
        assert!(!output.contains("CheckError"));
    }
}
