pub mod client;
pub mod config;
pub mod errors;
pub mod naming;
pub(crate) mod ts_utils;
pub mod typescript;

pub use config::{Config, Naming, NamingCase, NamespaceStyle};
pub use teleport_core::HttpMethod;

use std::path::Path;

use specta::ResolvedTypes;
use specta::datatype::DataType;

/// Metadata for a single procedure used internally by the generator.
#[derive(Debug, Clone)]
pub(crate) struct ProcedureInfo {
    /// Fully qualified name, e.g. `"users.getUser"`.
    pub name: String,
    /// HTTP method derived from the procedure type.
    pub method: HttpMethod,
    /// Route path, e.g. `"/rpc/users.getUser"`.
    pub path: String,
    /// Doc comment from the Rust source.
    pub doc: String,
    /// Specta type info for the input parameter.
    pub input_type: DataType,
    /// Specta type info for the output type.
    pub output_type: DataType,
    /// Specta type info for the error detail type.
    pub error_type: DataType,
}

/// One-liner for export binaries: collects all `#[remote]` procedures and generates TypeScript.
///
/// Replaces the manual `ProcedureInfo` construction boilerplate by iterating
/// `inventory` registrations, resolving types, and writing output files.
///
/// # Errors
///
/// Returns an error if type resolution or file writing fails.
#[allow(clippy::print_stderr)]
pub fn export_from_inventory(config: &Config) -> Result<(), GenerateError> {
    let mut types = specta::Types::default();
    let mut procedures = Vec::new();

    for reg in inventory::iter::<teleport_core::ProcedureRegistration> {
        let name = reg.name();
        let path = format!("{}/{}", config.route_prefix, name);
        let info = ProcedureInfo {
            name,
            method: reg.method,
            path,
            doc: reg.doc.to_owned(),
            input_type: (reg.input_type)(&mut types),
            output_type: (reg.output_type)(&mut types),
            error_type: (reg.error_type)(&mut types),
        };
        procedures.push(info);
    }

    if procedures.is_empty() {
        eprintln!("teleport-rs warning: no procedures found. Did you import all modules containing #[remote] functions?");
    }

    let resolved = specta::ResolvedTypes::from_resolved_types(types);
    generate(config, &procedures, &resolved)
}

/// Generate TypeScript bindings from collected procedure metadata.
///
/// Writes four files to `config.output_dir`:
/// - `types.ts` — all input/output structs and enums
/// - `errors.ts` — `AppError<T>`, `TransportError`, `RpcResult`, procedure-specific error types
/// - `client.ts` — namespaced client functions calling the `rpc` helper
/// - `index.ts` — barrel re-export of all generated modules
///
/// Files are only written when their content has actually changed, to avoid
/// unnecessary HMR triggers in the frontend dev server.
///
/// # Errors
///
/// Returns an error if the output directory cannot be created or files cannot be written.
fn generate(
    config: &Config,
    procedures: &[ProcedureInfo],
    resolved_types: &ResolvedTypes,
) -> Result<(), GenerateError> {
    std::fs::create_dir_all(&config.output_dir).map_err(GenerateError::CreateDir)?;

    let types_content = typescript::generate_types(resolved_types)?;
    let errors_content = errors::generate_errors(procedures, config, resolved_types)?;
    let client_content = client::generate_client(procedures, config, resolved_types)?;

    write_if_changed(&config.output_dir.join("types.ts"), &types_content)?;
    write_if_changed(&config.output_dir.join("errors.ts"), &errors_content)?;
    write_if_changed(&config.output_dir.join("client.ts"), &client_content)?;

    let index_content = "\
// Auto-generated by teleport-rs. DO NOT EDIT.

export * from \"./types\";
export * from \"./errors\";
export * from \"./client\";
";
    write_if_changed(&config.output_dir.join("index.ts"), index_content)?;

    Ok(())
}

/// Write `content` to `path` only if the file does not already contain the
/// same bytes. This avoids touching the mtime and triggering unnecessary
/// Vite HMR cycles.
fn write_if_changed(path: &Path, content: &str) -> Result<(), GenerateError> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == content
    {
        return Ok(());
    }
    std::fs::write(path, content).map_err(|source| GenerateError::WriteFile {
        path: path.to_path_buf(),
        source,
    })
}

/// Errors that can occur during TypeScript generation.
#[derive(Debug)]
pub enum GenerateError {
    /// Failed to create the output directory.
    CreateDir(std::io::Error),
    /// Failed to write a generated file.
    WriteFile { path: std::path::PathBuf, source: std::io::Error },
    /// Specta type export failed.
    TypeExport(String),
}

impl std::fmt::Display for GenerateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CreateDir(err) => write!(f, "failed to create output directory: {err}"),
            Self::WriteFile { path, source } => {
                write!(f, "failed to write {}: {source}", path.display())
            }
            Self::TypeExport(msg) => write!(f, "type export failed: {msg}"),
        }
    }
}

impl std::error::Error for GenerateError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::CreateDir(err) | Self::WriteFile { source: err, .. } => Some(err),
            Self::TypeExport(_) => None,
        }
    }
}
