mod adapter;
pub mod client;
pub mod config;
pub mod errors;
pub mod naming;
pub(crate) mod ts_utils;
pub mod typescript;

pub use config::{Config, NamespaceStyle, Naming, NamingCase};
pub use teleport_contract::{
    AuthMode, ContractBundle, FieldsContract, HttpMethod, InputEncoding, NamedFieldContract,
    NamedTypeContract, NamedTypeKind, PrimitiveType, ProcedureContract, ProcedureKind, TypeExpr,
    UnnamedFieldContract, VariantContract,
};

/// Shared "auto-generated, do not edit" banner prepended to every file
/// `teleport-build` emits. Deliberately has no trailing newline.
pub(crate) const GENERATED_HEADER: &str = "// Auto-generated by teleport-rs. DO NOT EDIT.";

use std::path::Path;

/// One-liner for Rust export binaries: collect all `#[remote]` procedures,
/// adapt them into a language-neutral contract bundle, and generate TS output.
#[allow(clippy::print_stderr)]
pub fn export_from_inventory(config: &Config) -> Result<(), GenerateError> {
    let bundle = contract_from_inventory(config)?;
    write_from_contract(config, &bundle)
}

/// Collect inventory registrations into a language-neutral contract bundle.
#[allow(clippy::print_stderr)]
pub fn contract_from_inventory(config: &Config) -> Result<ContractBundle, GenerateError> {
    adapter::contract_from_inventory(config)
}

/// Generate TypeScript bindings from a contract bundle and write them to disk.
pub fn write_from_contract(config: &Config, bundle: &ContractBundle) -> Result<(), GenerateError> {
    std::fs::create_dir_all(&config.output_dir).map_err(GenerateError::CreateDir)?;

    let types_content = with_context("types.ts", || typescript::generate_types(bundle))?;
    let errors_content = with_context("errors.ts", || errors::generate_errors(bundle, config))?;
    let client_content = with_context("client.ts", || client::generate_client(bundle, config))?;

    write_if_changed(&config.output_dir.join("types.ts"), &types_content)?;
    write_if_changed(&config.output_dir.join("errors.ts"), &errors_content)?;
    write_if_changed(&config.output_dir.join("client.ts"), &client_content)?;

    let index_content = "\
// Auto-generated by teleport-rs. DO NOT EDIT.

export * from \"./types\";
export * from \"./errors\";
export * from \"./client\";
";
    write_if_changed(&config.output_dir.join("index.ts"), index_content)?;

    Ok(())
}

/// Generate TypeScript bindings in-memory without writing to disk.
pub fn generate_from_contract(
    config: &Config,
    bundle: &ContractBundle,
) -> Result<GeneratedFiles, GenerateError> {
    Ok(GeneratedFiles {
        types_ts: with_context("types.ts", || typescript::generate_types(bundle))?,
        errors_ts: with_context("errors.ts", || errors::generate_errors(bundle, config))?,
        client_ts: with_context("client.ts", || client::generate_client(bundle, config))?,
        index_ts: "\
// Auto-generated by teleport-rs. DO NOT EDIT.

export * from \"./types\";
export * from \"./errors\";
export * from \"./client\";
"
        .to_owned(),
    })
}

/// In-memory output of the TS generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFiles {
    pub types_ts: String,
    pub errors_ts: String,
    pub client_ts: String,
    pub index_ts: String,
}

fn with_context<F>(file: &'static str, f: F) -> Result<String, GenerateError>
where
    F: FnOnce() -> Result<String, GenerateError>,
{
    f().map_err(|e| match e {
        GenerateError::TypeExport(msg) => {
            GenerateError::TypeExport(format!("while generating {file}: {msg}"))
        }
        other => other,
    })
}

fn write_if_changed(path: &Path, content: &str) -> Result<(), GenerateError> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == content
    {
        return Ok(());
    }
    std::fs::write(path, content).map_err(|source| GenerateError::WriteFile {
        path: path.to_path_buf(),
        source,
    })
}

/// Errors that can occur during TypeScript generation.
#[derive(Debug)]
pub enum GenerateError {
    /// Failed to create the output directory.
    CreateDir(std::io::Error),
    /// Failed to write a generated file.
    WriteFile {
        path: std::path::PathBuf,
        source: std::io::Error,
    },
    /// Exported contract could not be serialized.
    SerializeContract(serde_json::Error),
    /// Type export failed.
    TypeExport(String),
}

impl std::fmt::Display for GenerateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CreateDir(err) => write!(f, "failed to create output directory: {err}"),
            Self::WriteFile { path, source } => {
                write!(f, "failed to write {}: {source}", path.display())
            }
            Self::SerializeContract(err) => write!(f, "failed to serialize contract: {err}"),
            Self::TypeExport(msg) => write!(f, "type export failed: {msg}"),
        }
    }
}

impl std::error::Error for GenerateError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::CreateDir(err) | Self::WriteFile { source: err, .. } => Some(err),
            Self::SerializeContract(err) => Some(err),
            Self::TypeExport(_) => None,
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use std::error::Error as _;

    use teleport_contract::{
        ContractBundle, NamedTypeContract, NamedTypeKind, PrimitiveType, ProcedureContract,
        ProcedureKind, TypeExpr,
    };

    use super::*;

    fn sample_bundle() -> ContractBundle {
        ContractBundle {
            version: teleport_contract::CONTRACT_VERSION.to_owned(),
            procedures: vec![ProcedureContract {
                name: "users.getUser".to_owned(),
                namespace: "users".to_owned(),
                method_name: "getUser".to_owned(),
                procedure_kind: ProcedureKind::Query,
                http_method: HttpMethod::Get,
                path: "/rpc/users.getUser".to_owned(),
                input_encoding: InputEncoding::QueryString,
                auth_mode: AuthMode::None,
                doc: "Fetch one user.".to_owned(),
                input_type: TypeExpr::Named {
                    name: "UserId".to_owned(),
                    generics: Vec::new(),
                },
                output_type: TypeExpr::Named {
                    name: "User".to_owned(),
                    generics: Vec::new(),
                },
                error_type: TypeExpr::Tuple(Vec::new()),
            }],
            types: vec![
                NamedTypeContract {
                    name: "UserId".to_owned(),
                    docs: String::new(),
                    generics: Vec::new(),
                    kind: NamedTypeKind::Alias(TypeExpr::Primitive(PrimitiveType::str)),
                },
                NamedTypeContract {
                    name: "User".to_owned(),
                    docs: String::new(),
                    generics: Vec::new(),
                    kind: NamedTypeKind::Struct(FieldsContract::Named(vec![
                        NamedFieldContract {
                            name: "id".to_owned(),
                            docs: String::new(),
                            optional: false,
                            ty: Some(TypeExpr::Primitive(PrimitiveType::str)),
                        },
                        NamedFieldContract {
                            name: "name".to_owned(),
                            docs: String::new(),
                            optional: false,
                            ty: Some(TypeExpr::Primitive(PrimitiveType::str)),
                        },
                    ])),
                },
            ],
        }
    }

    #[test]
    fn generate_from_contract_returns_all_expected_files() {
        let config = Config::new("generated");
        let files = generate_from_contract(&config, &sample_bundle()).expect("generate files");

        assert!(files.types_ts.starts_with(GENERATED_HEADER));
        assert!(files.types_ts.contains("export type UserId = string;"));
        assert!(files.errors_ts.starts_with(GENERATED_HEADER));
        assert!(files.client_ts.contains("export function users_getUser"));
        assert_eq!(
            files.index_ts,
            "// Auto-generated by teleport-rs. DO NOT EDIT.\n\nexport * from \"./types\";\nexport * from \"./errors\";\nexport * from \"./client\";\n"
        );
    }

    #[test]
    fn write_from_contract_skips_unchanged_read_only_files() {
        let tempdir = tempfile::tempdir().expect("create tempdir");
        let config = Config::new(tempdir.path());
        let bundle = sample_bundle();

        write_from_contract(&config, &bundle).expect("initial write");

        let files = ["types.ts", "errors.ts", "client.ts", "index.ts"]
            .map(|name| tempdir.path().join(name));
        let original_permissions = files
            .iter()
            .map(|path| {
                let metadata = std::fs::metadata(path).expect("stat generated file");
                let original = metadata.permissions();
                let mut read_only = original.clone();
                read_only.set_readonly(true);
                std::fs::set_permissions(path, read_only).expect("set readonly");
                (path.clone(), original)
            })
            .collect::<Vec<_>>();

        write_from_contract(&config, &bundle).expect("unchanged readonly write");

        for (path, permissions) in original_permissions {
            std::fs::set_permissions(path, permissions).expect("restore permissions");
        }
    }

    #[test]
    fn with_context_wraps_type_export_errors_but_preserves_other_kinds() {
        let type_error = with_context("types.ts", || {
            Err(GenerateError::TypeExport("boom".to_owned()))
        })
        .expect_err("type export should fail");
        assert_eq!(
            type_error.to_string(),
            "type export failed: while generating types.ts: boom"
        );

        let io_error = std::io::Error::other("disk full");
        let create_dir = with_context("types.ts", || Err(GenerateError::CreateDir(io_error)))
            .expect_err("create dir should fail");
        assert!(matches!(create_dir, GenerateError::CreateDir(_)));
    }

    #[test]
    fn write_if_changed_reports_target_path_on_write_failure() {
        let tempdir = tempfile::tempdir().expect("create tempdir");
        let path = tempdir.path().join("missing").join("types.ts");

        let err = write_if_changed(&path, "content").expect_err("write should fail");
        match err {
            GenerateError::WriteFile { path: err_path, .. } => assert_eq!(err_path, path),
            other => panic!("unexpected error variant: {other}"),
        }
    }

    #[test]
    fn generate_error_source_tracks_wrapped_io_errors() {
        let io_error = std::io::Error::other("denied");
        let generate_error = GenerateError::CreateDir(io_error);
        assert!(generate_error.source().is_some());

        let type_export = GenerateError::TypeExport("boom".to_owned());
        assert!(type_export.source().is_none());
    }
}
